-- ============================================================================
--           Flattening Query for TMP_DF9 Benchmark Database
-- ============================================================================
-- File: `flatten_df9.sql`
-- Date: 2025-06-10
-- Author: Rudolf Cesaretti
-- Version: v2.0
--
-- Description:
-- This query joins the 18 core data tables from the tmp_df9 schema into a
-- single wide-format table. It uses LEFT JOINs from the central "tblSSN"
-- table to ensure all site records are preserved.
--
-- All columns are explicitly aliased to prevent name collisions and provide
-- clarity on the origin of each field in the final flattened table.
--
-- This version has been corrected to:
-- 1.  EXPAND 'fieldWorkers' and 'labAnalysts' into boolean indicator columns
--     for use as categorical/dummy/control variables in stats/ML/DL models.
-- 2.  ORDER ALL COLUMNS based on the exact sequence of TMP database variables
--     specified throughout the legacy TMP Electronic Files metadata.
-- ============================================================================

WITH
"pivoted_fieldWorkers" AS (
  SELECT
    "SSN",
    BOOL_OR("personnelCode" = 1) AS "fieldWorkers_Millon_R",
    BOOL_OR("personnelCode" = 2) AS "fieldWorkers_Drewitt_B",
    BOOL_OR("personnelCode" = 3) AS "fieldWorkers_Bennyhoff",
    BOOL_OR("personnelCode" = 4) AS "fieldWorkers_Banos",
    BOOL_OR("personnelCode" = 5) AS "fieldWorkers_Cowgill",
    BOOL_OR("personnelCode" = 6) AS "fieldWorkers_Spence",
    BOOL_OR("personnelCode" = 7) AS "fieldWorkers_Wallrath",
    BOOL_OR("personnelCode" = 8) AS "fieldWorkers_Marino",
    BOOL_OR("personnelCode" = 9) AS "fieldWorkers_Barbour",
    BOOL_OR("personnelCode" = 10) AS "fieldWorkers_deLucio_A",
    BOOL_OR("personnelCode" = 11) AS "fieldWorkers_deLucio_J",
    BOOL_OR("personnelCode" = 12) AS "fieldWorkers_Blucher",
    BOOL_OR("personnelCode" = 13) AS "fieldWorkers_Hungerford",
    BOOL_OR("personnelCode" = 14) AS "fieldWorkers_Sutherland",
    BOOL_OR("personnelCode" = 15) AS "fieldWorkers_Wilkerson",
    BOOL_OR("personnelCode" = 16) AS "fieldWorkers_Sharnoff",
    BOOL_OR("personnelCode" = 17) AS "fieldWorkers_Sanchez",
    BOOL_OR("personnelCode" = 18) AS "fieldWorkers_Fletcher",
    BOOL_OR("personnelCode" = 19) AS "fieldWorkers_Kolb",
    BOOL_OR("personnelCode" = 20) AS "fieldWorkers_Millon_C",
    BOOL_OR("personnelCode" = 21) AS "fieldWorkers_Dow",
    BOOL_OR("personnelCode" = 22) AS "fieldWorkers_deLucio_M",
    BOOL_OR("personnelCode" = 23) AS "fieldWorkers_Shankman",
    BOOL_OR("personnelCode" = 24) AS "fieldWorkers_Dodds",
    BOOL_OR("personnelCode" = 26) AS "fieldWorkers_Quisenberry",
    BOOL_OR("personnelCode" = 27) AS "fieldWorkers_West_M",
    BOOL_OR("personnelCode" = 28) AS "fieldWorkers_Bruhns_D",
    BOOL_OR("personnelCode" = 29) AS "fieldWorkers_Bruhns_K",
    BOOL_OR("personnelCode" = 30) AS "fieldWorkers_Duran"
  FROM
    tmp_df9."fieldWorkers"
  GROUP BY
    "SSN"
),
"pivoted_labAnalysts" AS (
  SELECT
    "SSN",
    BOOL_OR("personnelCode" = 1) AS "labAnalysts_Millon_R",
    BOOL_OR("personnelCode" = 2) AS "labAnalysts_Drewitt_B",
    BOOL_OR("personnelCode" = 3) AS "labAnalysts_Bennyhoff",
    BOOL_OR("personnelCode" = 4) AS "labAnalysts_Banos",
    BOOL_OR("personnelCode" = 5) AS "labAnalysts_Cowgill",
    BOOL_OR("personnelCode" = 6) AS "labAnalysts_Spence",
    BOOL_OR("personnelCode" = 7) AS "labAnalysts_Wallrath",
    BOOL_OR("personnelCode" = 8) AS "labAnalysts_Marino",
    BOOL_OR("personnelCode" = 9) AS "labAnalysts_Barbour",
    BOOL_OR("personnelCode" = 10) AS "labAnalysts_deLucio_A",
    BOOL_OR("personnelCode" = 11) AS "labAnalysts_deLucio_J",
    BOOL_OR("personnelCode" = 12) AS "labAnalysts_Blucher",
    BOOL_OR("personnelCode" = 13) AS "labAnalysts_Hungerford",
    BOOL_OR("personnelCode" = 14) AS "labAnalysts_Sutherland",
    BOOL_OR("personnelCode" = 15) AS "labAnalysts_Wilkerson",
    BOOL_OR("personnelCode" = 16) AS "labAnalysts_Sharnoff",
    BOOL_OR("personnelCode" = 17) AS "labAnalysts_Sanchez",
    BOOL_OR("personnelCode" = 18) AS "labAnalysts_Fletcher",
    BOOL_OR("personnelCode" = 19) AS "labAnalysts_Kolb",
    BOOL_OR("personnelCode" = 25) AS "labAnalysts_Drewitt_W",
    BOOL_OR("personnelCode" = 26) AS "labAnalysts_Quisenberry",
    BOOL_OR("personnelCode" = 27) AS "labAnalysts_West_M",
    BOOL_OR("personnelCode" = 30) AS "labAnalysts_Duran",
    BOOL_OR("personnelCode" = 31) AS "labAnalysts_West_E"
  FROM
    tmp_df9."labAnalysts"
  GROUP BY
    "SSN"
)
SELECT
    t1."SSN" AS "SSN",
    t1."site" AS "site",
    t1."subsite" AS "subsite",
    t1."unit" AS "unit",
    t1."northing" AS "northing",
    t1."easting" AS "easting",
    t4."collectionYear" AS "collectionYear",
    t4."collectionQuarter" AS "collectionQuarter",
    COALESCE(t11."fieldWorkers_Millon_R", FALSE) AS "fieldWorkers_Millon_R",
    COALESCE(t11."fieldWorkers_Drewitt_B", FALSE) AS "fieldWorkers_Drewitt_B",
    COALESCE(t11."fieldWorkers_Bennyhoff", FALSE) AS "fieldWorkers_Bennyhoff",
    COALESCE(t11."fieldWorkers_Banos", FALSE) AS "fieldWorkers_Banos",
    COALESCE(t11."fieldWorkers_Cowgill", FALSE) AS "fieldWorkers_Cowgill",
    COALESCE(t11."fieldWorkers_Spence", FALSE) AS "fieldWorkers_Spence",
    COALESCE(t11."fieldWorkers_Wallrath", FALSE) AS "fieldWorkers_Wallrath",
    COALESCE(t11."fieldWorkers_Marino", FALSE) AS "fieldWorkers_Marino",
    COALESCE(t11."fieldWorkers_Barbour", FALSE) AS "fieldWorkers_Barbour",
    COALESCE(t11."fieldWorkers_deLucio_A", FALSE) AS "fieldWorkers_deLucio_A",
    COALESCE(t11."fieldWorkers_deLucio_J", FALSE) AS "fieldWorkers_deLucio_J",
    COALESCE(t11."fieldWorkers_Blucher", FALSE) AS "fieldWorkers_Blucher",
    COALESCE(t11."fieldWorkers_Hungerford", FALSE) AS "fieldWorkers_Hungerford",
    COALESCE(t11."fieldWorkers_Sutherland", FALSE) AS "fieldWorkers_Sutherland",
    COALESCE(t11."fieldWorkers_Wilkerson", FALSE) AS "fieldWorkers_Wilkerson",
    COALESCE(t11."fieldWorkers_Sharnoff", FALSE) AS "fieldWorkers_Sharnoff",
    COALESCE(t11."fieldWorkers_Sanchez", FALSE) AS "fieldWorkers_Sanchez",
    COALESCE(t11."fieldWorkers_Fletcher", FALSE) AS "fieldWorkers_Fletcher",
    COALESCE(t11."fieldWorkers_Kolb", FALSE) AS "fieldWorkers_Kolb",
    COALESCE(t11."fieldWorkers_Millon_C", FALSE) AS "fieldWorkers_Millon_C",
    COALESCE(t11."fieldWorkers_Dow", FALSE) AS "fieldWorkers_Dow",
    COALESCE(t11."fieldWorkers_deLucio_M", FALSE) AS "fieldWorkers_deLucio_M",
    COALESCE(t11."fieldWorkers_Shankman", FALSE) AS "fieldWorkers_Shankman",
    COALESCE(t11."fieldWorkers_Dodds", FALSE) AS "fieldWorkers_Dodds",
    COALESCE(t11."fieldWorkers_Quisenberry", FALSE) AS "fieldWorkers_Quisenberry",
    COALESCE(t11."fieldWorkers_West_M", FALSE) AS "fieldWorkers_West_M",
    COALESCE(t11."fieldWorkers_Bruhns_D", FALSE) AS "fieldWorkers_Bruhns_D",
    COALESCE(t11."fieldWorkers_Bruhns_K", FALSE) AS "fieldWorkers_Bruhns_K",
    COALESCE(t11."fieldWorkers_Duran", FALSE) AS "fieldWorkers_Duran",
    t2."lastBuildPhase" AS "lastBuildPhase",
    t2."burials" AS "burials",
    t2."midden" AS "midden",
    t15."stoneQuant" AS "stoneQuant",
    t15."stoneDist" AS "stoneDist",
    t15."stoneCut" AS "stoneCut",
    t15."lajas" AS "lajas",
    t15."tepetate" AS "tepetate",
    t15."adobe" AS "adobe",
    t15."xalnene" AS "xalnene",
    t15."cascajo" AS "cascajo",
    t15."concrete" AS "concrete",
    t15."plasterUnpaint" AS "plasterUnpaint",
    t15."plasterPaint" AS "plasterPaint",
    t15."burntClay" AS "burntClay",
    t15."almena" AS "almena",
    t15."burnedStruct" AS "burnedStruct",
    t15."floors" AS "floors",
    t15."walls" AS "walls",
    t15."drains" AS "drainSitu",
    t15."wallFixtures" AS "wallFixSitu",
    t15."murals" AS "murals",
    t15."columns" AS "columns",
    t15."taludes" AS "taludes",
    t15."tableros" AS "tableros",
    t15."floorMaterial" AS "floorMaterial",
    t15."wallCoreStone" AS "wallCoreStone",
    t15."wallCoreOthMat" AS "wallCoreOthMat",
    t15."wallFacing" AS "wallFacing",
    t2."intrusiveSherd" AS "intrusiveSherd",
    t2."height" AS "height",
    t3."arch1PMic" AS "arch1PMic",
    t3."arch1McTl" AS "arch1McTl",
    t3."arch1XlMe" AS "arch1XlMe",
    t3."arch1Oxto" AS "arch1Oxto",
    t3."arch2PMic" AS "arch2PMic",
    t3."arch2McTl" AS "arch2McTl",
    t3."arch2XlMe" AS "arch2XlMe",
    t3."arch2Oxto" AS "arch2Oxto",
    t3."constructQual" AS "constructQual",
    t3."func1PMic" AS "func1PMic",
    t3."func1McTl" AS "func1McTl",
    t3."func1XlMe" AS "func1XlMe",
    t3."func1Oxto" AS "func1Oxto",
    t3."func2PMic" AS "func2PMic",
    t3."func2McTl" AS "func2McTl",
    t3."func2XlMe" AS "func2XlMe",
    t3."func2Oxto" AS "func2Oxto",
    t16."archInt1PaTz" AS "Cmplx_archInt1PaTz",
    t16."archInt1McTl" AS "Cmplx_archInt1McTl",
    t16."archInt1XlMt" AS "Cmplx_archInt1XlMt",
    t16."archInt2PaTz" AS "Cmplx_archInt2PaTz",
    t16."archInt2McTl" AS "Cmplx_archInt2McTl",
    t16."archInt2XlMt" AS "Cmplx_archInt2XlMt",
    t16."funcIntPaTz" AS "Cmplx_funcIntPaTz",
    t16."funcIntMcTl" AS "Cmplx_funcIntMcTl",
    t16."funcIntXlMt" AS "Cmplx_funcIntXlMt",
    t16."funcResPaTz" AS "Cmplx_funcResPaTz",
    t16."funcResMcTl" AS "Cmplx_funcResMcTl",
    t16."funcResXlMt" AS "Cmplx_funcResXlMt",
    t16."funcTmpPaTz" AS "Cmplx_funcTmpPaTz",
    t16."funcTmpMcTl" AS "Cmplx_funcTmpMcTl",
    t16."funcTmpXlMt" AS "Cmplx_funcTmpXlMt",
    t16."funcCivPaTz" AS "Cmplx_funcCivPaTz",
    t16."funcCivMcTl" AS "Cmplx_funcCivMcTl",
    t16."funcCivXlMt" AS "Cmplx_funcCivXlMt",
    t16."funcOthXlMt" AS "Cmplx_funcOthXlMt",
    t16."complexNum" AS "Cmplx_Num",
    t16."complexUnit" AS "Cmplx_Unit",
    t10."macroComplexNum" AS "MCmplx_Num",
    t10."macroComplexUnit" AS "MCmplx_Unit",
    t10."presPaTz" AS "MCmplx_presPaTz",
    t10."presMcTl" AS "MCmplx_presMcTl",
    t10."presXlMt" AS "MCmplx_presXlMt",
    t10."funcIntPaTz" AS "MCmplx_funcIntPaTz",
    t10."funcIntMcTl" AS "MCmplx_funcIntMcTl",
    t10."funcIntXlMt" AS "MCmplx_funcIntXlMt",
    t3."neighborhoodChar" AS "neighborhoodChar",
    t15."freeStandWall" AS "freeStandWall",
    t15."wells" AS "wells",
    t15."jagueys" AS "jagueyArch",
    t15."puestos" AS "puestos",
    t9."milpa" AS "milpa",
    t9."barley" AS "barley",
    t9."beans" AS "beans",
    t9."alfalfaCut" AS "alfalfaCut",
    t9."alfalfaUncut" AS "alfalfaUncut",
    t9."nopales" AS "nopales",
    t9."magueys" AS "magueys",
    t9."fallow" AS "fallow",
    t9."uncultivate" AS "uncultivate",
    t9."cropWater" AS "cropWater",
    t9."plowing" AS "plowing",
    t9."pitCultivate" AS "pitCultivate",
    t9."pitLoot" AS "pitLoot",
    t9."archaeoExcRest" AS "archaeoExcRest",
    t9."pitMisc" AS "pitMisc",
    t9."quarrying" AS "quarrying",
    t9."stoneClearing" AS "stoneClearing",
    t9."landLeveling" AS "landLeveling",
    t9."terracing" AS "terracing",
    t9."ditching" AS "ditching",
    t9."roadOrRail" AS "roadOrRail",
    t9."recentWall" AS "recentWall",
    t9."stoneRows" AS "stoneRows",
    t9."recentBuild" AS "recentBuild",
    t9."dam" AS "dam",
    t9."jaguey" AS "jagueyMod",
    t9."erosion" AS "erosion",
    t9."silting" AS "silting",
    t9."siteAlteration" AS "siteAlteration",
    t2."slope" AS "slope",
    t13."groundstoneField" AS "groundstoneField",
    t13."obsidianField" AS "obsidianField",
    t6."manos" AS "manos",
    t6."metates" AS "metates",
    t6."mortars" AS "mortars",
    t6."pestles" AS "pestles",
    t6."plasterSmoothers" AS "plasterSmoothers",
    t6."plumbBobs" AS "plumbBobs",
    t6."wallFixtures" AS "wallFixSurf",
    t6."fireGods" AS "fireGods",
    t6."sculptureFrags" AS "sculptureFrags",
    t6."hammerStones" AS "hammerStones",
    t6."slingStones" AS "slingStones",
    t6."smoothStones" AS "smoothStones",
    t6."whetStones" AS "whetStones",
    t6."palettes" AS "palettes",
    t6."celts" AS "celts",
    t6."lajasReworked" AS "lajasReworked",
    t6."anvils" AS "anvils",
    t6."drains" AS "drainSurf",
    t6."drainCovers" AS "drainCovers",
    t6."groundstoneOther" AS "groundstoneOther",
    t5."obsidianTot" AS "obsidianTot",
    t5."obsidianBlades" AS "obsidianBlades",
    t5."obsidianWaste" AS "obsidianWaste",
    t5."obsidianScrapers" AS "obsidianScrapers",
    t5."obsidianPoints" AS "obsidianPoints",
    t5."obsidianCores" AS "obsidianCores",
    t5."obsidianKnives" AS "obsidianKnives",
    t5."obsidianEccentrics" AS "obsidianEccentrics",
    t5."obsidianMagueyS" AS "obsidianMagueyS",
    t5."obsidianUtFlake" AS "obsidianUtFlake",
    t5."obsidianNodules" AS "obsidianNodules",
    t5."basaltTot" AS "basaltTot",
    t5."basaltTools" AS "basaltTools",
    t5."chert" AS "chert",
    t5."quartz" AS "quartz",
    t6."slateTot" AS "slateTot",
    t6."slatePainted" AS "slatePainted",
    t6."alabaster" AS "alabaster",
    t6."serpentine" AS "serpentine",
    t6."jade" AS "jade",
    t14."workedBone" AS "workedBone",
    t14."shellTot" AS "shellTot",
    t14."shellWorked" AS "shellWorked",
    t17."figTot" AS "figTot",
    t17."figHead" AS "figHead",
    t17."figPPat" AS "figPPat",
    t17."figPatl" AS "figPatl",
    t17."figTzac" AS "figTzac",
    t17."figMicc" AS "figMicc",
    t17."figTlam" AS "figTlam",
    t17."figXola" AS "figXola",
    t17."figMete" AS "figMete",
    t17."figTolt" AS "figTolt",
    t17."figAzte" AS "figAzte",
    t17."figPupp" AS "figPupp",
    t17."spindleWhorl" AS "spindleWhorl",
    t17."sealStamp" AS "sealStamp",
    t17."earSpool" AS "earSpool",
    t17."whistle" AS "whistle",
    t17."flute" AS "flute",
    COALESCE(t12."labAnalysts_Millon_R", FALSE) AS "labAnalysts_Millon_R",
    COALESCE(t12."labAnalysts_Drewitt_B", FALSE) AS "labAnalysts_Drewitt_B",
    COALESCE(t12."labAnalysts_Bennyhoff", FALSE) AS "labAnalysts_Bennyhoff",
    COALESCE(t12."labAnalysts_Banos", FALSE) AS "labAnalysts_Banos",
    COALESCE(t12."labAnalysts_Cowgill", FALSE) AS "labAnalysts_Cowgill",
    COALESCE(t12."labAnalysts_Spence", FALSE) AS "labAnalysts_Spence",
    COALESCE(t12."labAnalysts_Wallrath", FALSE) AS "labAnalysts_Wallrath",
    COALESCE(t12."labAnalysts_Marino", FALSE) AS "labAnalysts_Marino",
    COALESCE(t12."labAnalysts_Barbour", FALSE) AS "labAnalysts_Barbour",
    COALESCE(t12."labAnalysts_deLucio_A", FALSE) AS "labAnalysts_deLucio_A",
    COALESCE(t12."labAnalysts_deLucio_J", FALSE) AS "labAnalysts_deLucio_J",
    COALESCE(t12."labAnalysts_Blucher", FALSE) AS "labAnalysts_Blucher",
    COALESCE(t12."labAnalysts_Hungerford", FALSE) AS "labAnalysts_Hungerford",
    COALESCE(t12."labAnalysts_Sutherland", FALSE) AS "labAnalysts_Sutherland",
    COALESCE(t12."labAnalysts_Wilkerson", FALSE) AS "labAnalysts_Wilkerson",
    COALESCE(t12."labAnalysts_Sharnoff", FALSE) AS "labAnalysts_Sharnoff",
    COALESCE(t12."labAnalysts_Sanchez", FALSE) AS "labAnalysts_Sanchez",
    COALESCE(t12."labAnalysts_Fletcher", FALSE) AS "labAnalysts_Fletcher",
    COALESCE(t12."labAnalysts_Kolb", FALSE) AS "labAnalysts_Kolb",
    COALESCE(t12."labAnalysts_Drewitt_W", FALSE) AS "labAnalysts_Drewitt_W",
    COALESCE(t12."labAnalysts_Quisenberry", FALSE) AS "labAnalysts_Quisenberry",
    COALESCE(t12."labAnalysts_West_M", FALSE) AS "labAnalysts_West_M",
    COALESCE(t12."labAnalysts_Duran", FALSE) AS "labAnalysts_Duran",
    COALESCE(t12."labAnalysts_West_E", FALSE) AS "labAnalysts_West_E",
    t4."analysisYear" AS "analysisYear",
    t4."analysisQuarter" AS "analysisQuarter",
    t13."ceramicField" AS "ceramicField",
    t2."ceramicAbundance" AS "ceramicAbundance",
    t17."candTot" AS "candTot",
    t17."candCoat" AS "candCoat",
    t17."candAtoy" AS "candAtoy",
    t17."candEXol" AS "candEXol",
    t17."candLXol" AS "candLXol",
    t17."candMete" AS "candMete",
    t17."candComm" AS "candComm",
    t7."burner3P" AS "burner3P",
    t7."coverHandled" AS "coverHandled",
    t2."areaSite" AS "areaSite",
    t8."totAll" AS "totAll",
    t8."totPrec" AS "totPrec",
    t8."totCuan" AS "totCuan",
    t8."totTezo" AS "totTezo",
    t8."totPatl" AS "totPatl",
    t8."totTzac" AS "totTzac",
    t8."totMicc" AS "totMicc",
    t8."totTlam" AS "totTlam",
    t8."totXola" AS "totXola",
    t8."totMete" AS "totMete",
    t8."totOxto" AS "totOxto",
    t8."totXome" AS "totXome",
    t8."totMaza" AS "totMaza",
    t8."totAzte" AS "totAzte",
    t7."censerTot" AS "censerTot",
    t7."censerPPat" AS "censerPPat",
    t7."censerPatl" AS "censerPatl",
    t7."censerTzac" AS "censerTzac",
    t7."censerMicc" AS "censerMicc",
    t7."censerTlam" AS "censerTlam",
    t7."censerXola" AS "censerXola",
    t7."censerMete" AS "censerMete",
    t7."censerOxto" AS "censerOxto",
    t7."censerXome" AS "censerXome",
    t7."censerMaza" AS "censerMaza",
    t7."censerAzte" AS "censerAzte",
    t7."toTot" AS "toTot",
    t7."toRegular" AS "toRegular",
    t7."toCoarse" AS "toCoarse",
    t7."smoTot" AS "smoTot",
    t7."smoTlam" AS "smoTlam",
    t7."smoXola" AS "smoXola",
    t7."smoMete" AS "smoMete",
    t7."ollaTot" AS "ollaTot",
    t7."ollaPatl" AS "ollaPatl",
    t7."ollaWedge" AS "ollaWedge",
    t7."ollaMicc" AS "ollaMicc",
    t7."ollaTlam" AS "ollaTlam",
    t7."ollaXola" AS "ollaXola",
    t7."ollaMete" AS "ollaMete",
    t7."comalTot" AS "comalTot",
    t7."comalPatl" AS "comalPatl",
    t7."comalTzac" AS "comalTzac",
    t7."comalMicc" AS "comalMicc",
    t7."comalTlam" AS "comalTlam",
    t7."comalXola" AS "comalXola",
    t7."comalMete" AS "comalMete",
    t7."comalOxto" AS "comalOxto",
    t7."comalPOxt" AS "comalPOxt",
    t7."nubbinTot" AS "nubbinTot",
    t7."nubbinPatl" AS "nubbinPatl",
    t7."nubbinApet" AS "nubbinApet",
    t7."nubbinInset" AS "nubbinInset",
    t7."nubbinFlush" AS "nubbinFlush",
    t7."nubbinAtoy" AS "nubbinAtoy",
    t7."nubbinXola" AS "nubbinXola",
    t7."nubbinMete" AS "nubbinMete",
    t7."shrdStamped" AS "shrdStamped",
    t7."shrdPlanoR" AS "shrdPlanoR",
    t7."shrdStucco" AS "shrdStucco",
    t7."shrdIncised" AS "shrdIncised",
    t7."foreignTot" AS "foreignTot",
    t7."mayaLow" AS "mayaLow",
    t7."mayaHigh" AS "mayaHigh",
    t7."huastec" AS "huastec",
    t7."tajin" AS "tajin",
    t7."gulfCoast" AS "gulfCoast",
    t7."monteAlban" AS "monteAlban",
    t7."oaxaca" AS "oaxaca",
    t7."foreignOther" AS "foreignOther",
    t7."adornos" AS "adornos",
    t7."minatures" AS "minatures",
    t7."copas" AS "copas",
    t7."matteWare" AS "matteWare",
    t7."granTot" AS "granTot",
    t7."granPMic" AS "granPMic",
    t7."granMicc" AS "granMicc",
    t7."granTlam" AS "granTlam",
    t7."granXola" AS "granXola",
    t7."granMete" AS "granMete",
    t17."ceramicDisk" AS "ceramicDisk",
    t13."obsidianSpencePhase1" AS "obsidianSpencePhase1",
    t13."obsidianSpencePhase2" AS "obsidianSpencePhase2",
    t13."ceramicKrotser" AS "ceramicKrotser",
    t13."figurineConcBarbour" AS "figurineConcBarbour",
    t2."areaStruct" AS "areaStruct",
    t3."insubstantialCount" AS "insubstantialCount",
    t3."boundInfoQual" AS "boundInfoQual"
FROM
    tmp_df9."location" AS t1
LEFT JOIN tmp_df9."description" AS t2 ON t1."SSN" = t2."SSN"
LEFT JOIN tmp_df9."archInterp" AS t3 ON t1."SSN" = t3."SSN"
LEFT JOIN tmp_df9."admin" AS t4 ON t1."SSN" = t4."SSN"
LEFT JOIN tmp_df9."lithicFlaked" AS t5 ON t1."SSN" = t5."SSN"
LEFT JOIN tmp_df9."lithicGround" AS t6 ON t1."SSN" = t6."SSN"
LEFT JOIN tmp_df9."cerVessel" AS t7 ON t1."SSN" = t7."SSN"
LEFT JOIN tmp_df9."cerPhTot" AS t8 ON t1."SSN" = t8."SSN"
LEFT JOIN tmp_df9."condition" AS t9 ON t1."SSN" = t9."SSN"
LEFT JOIN tmp_df9."complexMacroData" AS t10 ON t1."SSN" = t10."SSN"
LEFT JOIN "pivoted_fieldWorkers" AS t11 ON t1."SSN" = t11."SSN"
LEFT JOIN "pivoted_labAnalysts" AS t12 ON t1."SSN" = t12."SSN"
LEFT JOIN tmp_df9."workshop" AS t13 ON t1."SSN" = t13."SSN"
LEFT JOIN tmp_df9."artifactOther" AS t14 ON t1."SSN" = t14."SSN"
LEFT JOIN tmp_df9."archMaterial" AS t15 ON t1."SSN" = t15."SSN"
LEFT JOIN tmp_df9."complexData" AS t16 ON t1."SSN" = t16."SSN"
LEFT JOIN tmp_df9."cerNonVessel" AS t17 ON t1."SSN" = t17."SSN"
LEFT JOIN tmp_df9."Plazas" AS t18 ON t1."SSN" = t18."SSN"
ORDER BY
    t1."SSN";
