name: Python Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          # Point to the CI-specific environment file.
          environment-file: envs/environment.yml
          # Activate the environment specified by the 'name:' field in the YAML file.
          activate-environment: digital_tmp_base
          use-mamba: true

      - name: Lint and Format Checks
        shell: bash -l {0}
        run: |
          echo "--- Running Ruff Linter ---"
          ruff check .

          echo "--- Running Ruff Formatter Check ---"
          ruff format --check .

          echo "--- Running SQLFluff Linter ---"
          sqlfluff lint . --dialect postgres

      - name: Run Pytest
        shell: bash -l {0}
        run: |
          echo "--- Running test suite ---"
          # This assumes your tests are in a 'tests/' directory.
          pytest tests/

      - name: Security Scan for Secrets
        shell: bash -l {0}
        run: |
          echo "--- Scanning for hardcoded secrets ---"
          if [ -f .secrets.baseline ]; then
            detect-secrets scan --baseline .secrets.baseline
          else
            detect-secrets scan
          fi

      - name: Code Complexity Analysis with Radon
        shell: bash -l {0}
        run: |
          echo "--- Analyzing code complexity ---"
          radon cc . -na -a -nc

          echo "--- Analyzing code maintainability ---"
          radon mi . -s -nb
